// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.1
// 	protoc        (unknown)
// source: xcommon/common.proto

package xcommon

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Bool int32

const (
	Bool_BOOL_UNSPECIFIED Bool = 0
	Bool_BOOL_YES         Bool = 1
	Bool_BOOL_NO          Bool = 2
)

// Enum value maps for Bool.
var (
	Bool_name = map[int32]string{
		0: "BOOL_UNSPECIFIED",
		1: "BOOL_YES",
		2: "BOOL_NO",
	}
	Bool_value = map[string]int32{
		"BOOL_UNSPECIFIED": 0,
		"BOOL_YES":         1,
		"BOOL_NO":          2,
	}
)

func (x Bool) Enum() *Bool {
	p := new(Bool)
	*p = x
	return p
}

func (x Bool) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Bool) Descriptor() protoreflect.EnumDescriptor {
	return file_xcommon_common_proto_enumTypes[0].Descriptor()
}

func (Bool) Type() protoreflect.EnumType {
	return &file_xcommon_common_proto_enumTypes[0]
}

func (x Bool) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Bool.Descriptor instead.
func (Bool) EnumDescriptor() ([]byte, []int) {
	return file_xcommon_common_proto_rawDescGZIP(), []int{0}
}

// CommonIn 通用请求包字段
type CommonIn struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 追踪Id
	TrackId string `protobuf:"bytes,1,opt,name=TrackId,proto3" json:"TrackId,omitempty"`
	// 客户端Id
	ClientId string `protobuf:"bytes,2,opt,name=ClientId,proto3" json:"ClientId,omitempty"`
	// 语言
	Lang string `protobuf:"bytes,5,opt,name=Lang,proto3" json:"Lang,omitempty"`
	// 令牌, 需要登录的接口必传
	Token string `protobuf:"bytes,3,opt,name=Token,proto3" json:"Token,omitempty"`
	// 用户Id, 可选字段, 客户端请求不传
	UserId        int64 `protobuf:"varint,4,opt,name=UserId,proto3" json:"UserId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommonIn) Reset() {
	*x = CommonIn{}
	mi := &file_xcommon_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommonIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonIn) ProtoMessage() {}

func (x *CommonIn) ProtoReflect() protoreflect.Message {
	mi := &file_xcommon_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonIn.ProtoReflect.Descriptor instead.
func (*CommonIn) Descriptor() ([]byte, []int) {
	return file_xcommon_common_proto_rawDescGZIP(), []int{0}
}

func (x *CommonIn) GetTrackId() string {
	if x != nil {
		return x.TrackId
	}
	return ""
}

func (x *CommonIn) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *CommonIn) GetLang() string {
	if x != nil {
		return x.Lang
	}
	return ""
}

func (x *CommonIn) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *CommonIn) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// CommonOut 通用回包字段
type CommonOut struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 状态码
	Code int32 `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	// 错误信息
	ErrMsg        string `protobuf:"bytes,2,opt,name=ErrMsg,proto3" json:"ErrMsg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommonOut) Reset() {
	*x = CommonOut{}
	mi := &file_xcommon_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommonOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonOut) ProtoMessage() {}

func (x *CommonOut) ProtoReflect() protoreflect.Message {
	mi := &file_xcommon_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonOut.ProtoReflect.Descriptor instead.
func (*CommonOut) Descriptor() ([]byte, []int) {
	return file_xcommon_common_proto_rawDescGZIP(), []int{1}
}

func (x *CommonOut) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CommonOut) GetErrMsg() string {
	if x != nil {
		return x.ErrMsg
	}
	return ""
}

var File_xcommon_common_proto protoreflect.FileDescriptor

var file_xcommon_common_proto_rawDesc = []byte{
	0x0a, 0x14, 0x78, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x78, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x22,
	0x82, 0x01, 0x0a, 0x08, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x49, 0x6e, 0x12, 0x18, 0x0a, 0x07,
	0x54, 0x72, 0x61, 0x63, 0x6b, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x54,
	0x72, 0x61, 0x63, 0x6b, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x4c, 0x61, 0x6e, 0x67, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x4c, 0x61, 0x6e, 0x67, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x16, 0x0a, 0x06,
	0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x55, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x22, 0x37, 0x0a, 0x09, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x4f, 0x75,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x04, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x45, 0x72, 0x72, 0x4d, 0x73, 0x67, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x45, 0x72, 0x72, 0x4d, 0x73, 0x67, 0x2a, 0x37, 0x0a,
	0x04, 0x42, 0x6f, 0x6f, 0x6c, 0x12, 0x14, 0x0a, 0x10, 0x42, 0x4f, 0x4f, 0x4c, 0x5f, 0x55, 0x4e,
	0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x42,
	0x4f, 0x4f, 0x4c, 0x5f, 0x59, 0x45, 0x53, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x42, 0x4f, 0x4f,
	0x4c, 0x5f, 0x4e, 0x4f, 0x10, 0x02, 0x42, 0x20, 0x5a, 0x1e, 0x67, 0x6f, 0x6d, 0x6f, 0x64, 0x2e,
	0x70, 0x72, 0x69, 0x2f, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x47, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x62,
	0x2f, 0x78, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_xcommon_common_proto_rawDescOnce sync.Once
	file_xcommon_common_proto_rawDescData = file_xcommon_common_proto_rawDesc
)

func file_xcommon_common_proto_rawDescGZIP() []byte {
	file_xcommon_common_proto_rawDescOnce.Do(func() {
		file_xcommon_common_proto_rawDescData = protoimpl.X.CompressGZIP(file_xcommon_common_proto_rawDescData)
	})
	return file_xcommon_common_proto_rawDescData
}

var file_xcommon_common_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_xcommon_common_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_xcommon_common_proto_goTypes = []any{
	(Bool)(0),         // 0: xcommon.Bool
	(*CommonIn)(nil),  // 1: xcommon.CommonIn
	(*CommonOut)(nil), // 2: xcommon.CommonOut
}
var file_xcommon_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_xcommon_common_proto_init() }
func file_xcommon_common_proto_init() {
	if File_xcommon_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_xcommon_common_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_xcommon_common_proto_goTypes,
		DependencyIndexes: file_xcommon_common_proto_depIdxs,
		EnumInfos:         file_xcommon_common_proto_enumTypes,
		MessageInfos:      file_xcommon_common_proto_msgTypes,
	}.Build()
	File_xcommon_common_proto = out.File
	file_xcommon_common_proto_rawDesc = nil
	file_xcommon_common_proto_goTypes = nil
	file_xcommon_common_proto_depIdxs = nil
}
