// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.1
// 	protoc        (unknown)
// source: xcommon/enum.proto

package xcommon

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 选择框是否为选择状态的枚举定义
type Mark int32

const (
	Mark_MARK_UNSPECIFIED Mark = 0
	Mark_MARK_ON          Mark = 1 // 是选择状态
	Mark_MARK_OFF         Mark = 2 // 不是选择状态
)

// Enum value maps for Mark.
var (
	Mark_name = map[int32]string{
		0: "MARK_UNSPECIFIED",
		1: "MARK_ON",
		2: "MARK_OFF",
	}
	Mark_value = map[string]int32{
		"MARK_UNSPECIFIED": 0,
		"MARK_ON":          1,
		"MARK_OFF":         2,
	}
)

func (x Mark) Enum() *Mark {
	p := new(Mark)
	*p = x
	return p
}

func (x Mark) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Mark) Descriptor() protoreflect.EnumDescriptor {
	return file_xcommon_enum_proto_enumTypes[0].Descriptor()
}

func (Mark) Type() protoreflect.EnumType {
	return &file_xcommon_enum_proto_enumTypes[0]
}

func (x Mark) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Mark.Descriptor instead.
func (Mark) EnumDescriptor() ([]byte, []int) {
	return file_xcommon_enum_proto_rawDescGZIP(), []int{0}
}

type Status int32

const (
	Status_STATUS_UNSPECIFIED Status = 0
	// 正常
	Status_STATUS_NORMAL Status = 1
	// 非正常
	Status_STATUS_ABNORMAL Status = 2
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_NORMAL",
		2: "STATUS_ABNORMAL",
	}
	Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"STATUS_NORMAL":      1,
		"STATUS_ABNORMAL":    2,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_xcommon_enum_proto_enumTypes[1].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_xcommon_enum_proto_enumTypes[1]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_xcommon_enum_proto_rawDescGZIP(), []int{1}
}

var File_xcommon_enum_proto protoreflect.FileDescriptor

var file_xcommon_enum_proto_rawDesc = []byte{
	0x0a, 0x12, 0x78, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x65, 0x6e, 0x75, 0x6d, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x78, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2a, 0x37, 0x0a,
	0x04, 0x4d, 0x61, 0x72, 0x6b, 0x12, 0x14, 0x0a, 0x10, 0x4d, 0x41, 0x52, 0x4b, 0x5f, 0x55, 0x4e,
	0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x4d,
	0x41, 0x52, 0x4b, 0x5f, 0x4f, 0x4e, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x4d, 0x41, 0x52, 0x4b,
	0x5f, 0x4f, 0x46, 0x46, 0x10, 0x02, 0x2a, 0x48, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x16, 0x0a, 0x12, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45,
	0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x11, 0x0a, 0x0d, 0x53, 0x54, 0x41, 0x54,
	0x55, 0x53, 0x5f, 0x4e, 0x4f, 0x52, 0x4d, 0x41, 0x4c, 0x10, 0x01, 0x12, 0x13, 0x0a, 0x0f, 0x53,
	0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x41, 0x42, 0x4e, 0x4f, 0x52, 0x4d, 0x41, 0x4c, 0x10, 0x02,
	0x42, 0x20, 0x5a, 0x1e, 0x67, 0x6f, 0x6d, 0x6f, 0x64, 0x2e, 0x70, 0x72, 0x69, 0x2f, 0x68, 0x65,
	0x6c, 0x6c, 0x6f, 0x47, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x62, 0x2f, 0x78, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_xcommon_enum_proto_rawDescOnce sync.Once
	file_xcommon_enum_proto_rawDescData = file_xcommon_enum_proto_rawDesc
)

func file_xcommon_enum_proto_rawDescGZIP() []byte {
	file_xcommon_enum_proto_rawDescOnce.Do(func() {
		file_xcommon_enum_proto_rawDescData = protoimpl.X.CompressGZIP(file_xcommon_enum_proto_rawDescData)
	})
	return file_xcommon_enum_proto_rawDescData
}

var file_xcommon_enum_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_xcommon_enum_proto_goTypes = []any{
	(Mark)(0),   // 0: xcommon.Mark
	(Status)(0), // 1: xcommon.Status
}
var file_xcommon_enum_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_xcommon_enum_proto_init() }
func file_xcommon_enum_proto_init() {
	if File_xcommon_enum_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_xcommon_enum_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_xcommon_enum_proto_goTypes,
		DependencyIndexes: file_xcommon_enum_proto_depIdxs,
		EnumInfos:         file_xcommon_enum_proto_enumTypes,
	}.Build()
	File_xcommon_enum_proto = out.File
	file_xcommon_enum_proto_rawDesc = nil
	file_xcommon_enum_proto_goTypes = nil
	file_xcommon_enum_proto_depIdxs = nil
}
